### ISSUE TITLE
Re: 'Changes to GOV.UK Frontend v5.0.0'

### ISSUE THREAD

**Issue by qua-1** [alphagov/govuk-frontend-docs#414]
Problem with 'Changes to GOV.UK Frontend v5.0.0' (https://frontend.design-system.service.gov.uk/changes-to-govuk-frontend-v5/)

The following sentence is confusing: 
"You’ll need to remove items, which include:"

It's confusing because the comma makes the instruction too vague: what items need to be removed?

I'm going to guess that what's intended is one of the following:
1. "You'll need to remove the following items:"
2. "You'll need to remove any items which include the following:"

(The comma is performing a non-restrictive effect on the clause when in reality we need a restrictive clause - one that tells us precisely what items need to be removed. "Which" can be used in restrictive clauses, so I don't know whether the writer intentionally wrote a non-restrictive clause with ", which" or mistakenly thought you had to precede "which" with a comma.)

**Comment by 36degrees** [comment]
Thanks for the feedback, Simone!

@claireashworth can you take a look and see if there are any changes we want to make off the back of this?

**Comment by claireashworth** [comment]
Thank you for your feedback.
I've raised a PR (#416) to make this change. The non-restrictive effect was originally on purpose due to this page being a summary which might not have had a full list of changes (but containing links to the full release notes). However, the items to remove is a complete list, so I've amended the lead in line as suggested.
